version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket cfn-training-takaoukudou-20210411 --output-template-file packaged-template.yml
      - cd ${CODEBUILD_SRC_DIR}
      - cd vue-project
      - npm i -g @mablhq/mabl-cli
      - npm i -g wait-on
      - npm install
      - npm run serve & wait-on http://localhost:8080
      - mabl auth activate-key f1fsSVxYjUW5oo2iyKkPRA
      - mabl auth info
      - mabl tests run --from-plan-id omBIwyV83bcjI8vH53tW3w-p
artifacts:
  files:
    - packaged-template.yml
  name: packaged-template.yml
