version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket cfn-training-takaoukudou-20210411 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
  name: packaged-template.yml
