version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket cfn-training-takaoukudou-20210411 --output-template-file packaged-template.yml
      - cd ${CODEBUILD_SRC_DIR}
      - cd vue-project
      - npm i -g @mablhq/mabl-cli
      - npm i
      - mabl auth activate-key b1crrVf7k4LYP80p9ubc1g
      - npm install wait-on
      - npm run serve &
      - mabl tests run --id XvqiWzLGhZaxeCi4lzcqxg-j --headless

artifacts:
  files:
    - packaged-template.yml
  name: packaged-template.yml
